version: "3.9"

x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  image: ai-engine:latest
  working_dir: /app
  environment:
    - PYTHONUNBUFFERED=1
  ports:
    - "8000:8000"

services:
  api-dev:
    <<: *common
    container_name: ai-engine-api-dev
    profiles: ["dev"]
    environment:
      - APP_ENV=development
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  api:
    <<: *common
    container_name: ai-engine-api
    profiles: ["prod"]
    environment:
      - APP_ENV=production
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2

